# Generated by Django 2.0.6 on 2018-06-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['country__name', 'name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['zone', 'name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
